[package]
name = "local"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
now = { path = "../now" }
serde = "1.0"
simd-json = "0.9.2"
log = "0.4"
weather_dirs = { path = "../weather_dirs" }
weather_error = { path = "../weather_error" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.48.*", features = ["Foundation", "System_Power", "Win32_System_Power", "Win32_Foundation"] }
