version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/requirements.in"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "/cargo.toml"
    schedule:
      interval: daily
  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: daily
