bin = [
    { name = "weatherd", path = "bin/weatherd.rs" },
    { name = "updater", path = "bin/updater.rs" },
]

[package]
name = "weather_core"
version = "2023.3.21"
edition = "2021"

[lib]
name = "weather_core"
crate-type = [
    "cdylib",
    "rlib",
]

[dependencies]
rayon = "1.7.0"
serde_json = "1.0"
sha256 = "1.1.2"
dirs = "5.0.0"
chrono = "0.4.23"
auto-launch = "0.4.0"
crossterm = "0.26.1"
futures-util = "0.3.27"
indicatif = "0.17.3"
iced = "0.8"

[dependencies.tokio]
version = "1.26.0"
features = [
    "full",
]

[dependencies.clap]
version = "4.1.8"
features = [
    "derive",
]

[dependencies.pyo3]
version = "0.18.1"
features = [
    "extension-module",
]

[dependencies.reqwest]
version = "0.11.14"
features = [
    "blocking",
    "json",
    "cookies",
    "stream",
]

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[target."cfg(target_os = \"windows\")".dependencies.windows]
version = "0.46.0"
features = [
    "Foundation",
    "Devices_Geolocation",
]
