bin = [
    { name = "weatherd", path = "bin/weatherd.rs" },
]

[package]
name = "weather_core"
version = "2023.3.17"
edition = "2021"

[lib]
name = "core"
crate-type = [
    "cdylib",
    "rlib",
]

[dependencies]
rayon = "1.7.0"
serde_json = "1.0"
sha256 = "1.1.2"
dirs = "4.0.0"
chrono = "0.4.23"
auto-launch = "0.4.0"

[dependencies.pyo3]
version = "0.18.1"
features = [
    "extension-module",
]

[dependencies.reqwest]
version = "0.11.14"
features = [
    "blocking",
    "json",
    "cookies",
]

[dependencies.serde]
version = "1.0"
features = [
    "derive",
]

[target."cfg(target_os = \"windows\")".dependencies.windows]
version = "0.46.0"
features = [
    "Foundation",
    "Devices_Geolocation",
]
