[[bin]]
required-features = ["support"]
name = "weatherd"
path = "bin/weatherd.rs"

[[bin]]
required-features = ["support"]
name = "updater"
path = "bin/updater.rs"

[[bin]]
required-features = ["support", "installer", "gui"]
name = "gui_installer"
path = "bin/gui_installer.rs"

[[bin]]
required-features = ["support", "installer"]
name = "installer"
path = "bin/installer.rs"

[[bin]]
name = "weather"
path = "bin/weather.rs"

[lib]
name = "weather_core"
crate-type = [
    "cdylib",
    "rlib",
]

[package]
name = "weather_core"
version = "2023.4.21"
edition = "2021"
authors = ["Ashwin Naren"]
rust-version = "1.60.0"
description = "Rust portions of weathercli"
readme = "README.md"
homepage = "https://arihant2math.github.io/weathercli/"
repository = "https://github.com/arihant2math/weathercli"

[build-dependencies]
winresource = "0.1"

[dependencies]
bincode = { version = "1.3.3", optional = true }
rayon = "1.7.*"
serde_json = "1.0.*"
sha2 = "0.10.*"
crossterm = "0.26.*"
futures-util = { version = "0.3.*", optional = true }
indicatif = { version = "0.17.*", optional = true }
iced = { version = "0.9.*", optional = true }
tokio = { version = "1.27.*", features = ["full"], optional = true }
clap = { version = "4.2.*", features = ["derive"], optional = true }
serde = { version = "1.0.*", features = ["derive"] }
reqwest = { version = "0.11.*", features = ["blocking", "json", "cookies"] }
thiserror = { version = "1", optional = true }
hex = "0.4.*"
image = "0.24.6"

[dev-dependencies]
rand = "0.8.5"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_users = { version = "0.4", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Com",
] }
winreg = "0.50.*"
windows = { version = "0.48.*", features = ["Foundation", "Devices_Geolocation"] }

[features]
support = ["dep:clap", "dep:tokio", "dep:futures-util", "dep:thiserror", "reqwest/stream", "dep:indicatif", "dep:bincode"]
installer = []
gui = ["dep:iced"]
default = ["gui", "support"]

[profile.release]
debug = true
