[package]
name = "weather_core"
version = "0.1.0"
edition = "2021"

[lib]
# The name of the native library. This is the name which will be used in Python to import the
# library (i.e. `import core`). If you change this, you must also change the name of the
# `#[pymodule]` in `src/lib.rs`.
name = "core"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use core;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.17.3", features = ["extension-module"] }
reqwest = { version = "0.11.13", features = ["blocking", "json"] }
rayon = "1.6.1"
serde = { version = "1.0.151", features = ["derive"] }
serde_json = "1.0.91"
sha256 = "1.1.1"
dirs = "4.0.0"

[dependencies.windows]
version = "0.44.0"
features = [
    "Foundation",
    "Devices_Geolocation"
]
