[[bin]]
name = "weatherd"
path = "bin/weatherd.rs"

[[bin]]
name = "updater"
path = "bin/updater.rs"

[[bin]]
name = "gui_installer"
path = "bin/gui_installer.rs"

[[bin]]
name = "installer"
path = "bin/installer.rs"

[lib]
name = "weather_core"
crate-type = [
    "cdylib",
    "rlib",
]

[package]
name = "weather_core"
version = "2023.4.6"
edition = "2021"
authors = ["Ashwin Naren"]
rust-version = "1.67.0"
description = "Rust portions of weathercli"
readme = "README.md"
homepage = "https://arihant2math.github.io/weathercli/"
repository = "https://github.com/arihant2math/weathercli"

[build-dependencies]
winresource = "0.1"

[dependencies]
rayon = "1.7.*"
serde_json = "1.0.*"
sha2 = "0.10.*"
crossterm = "0.26.*"
futures-util = "0.3.*"
indicatif = "0.17.*"
iced = "0.8.*"
bincode = "1.3.*"
tokio = { version = "1.27.*", features = ["full"] }
clap = { version = "4.2.*", features = ["derive"] }
pyo3 = { version = "0.18.*", features = ["extension-module"] }
serde = { version = "1.0.*", features = ["derive"] }
reqwest = { version = "0.11.*", features = ["blocking", "json", "cookies", "stream"] }
thiserror = "1"
hex = "0.4.*"

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[target.'cfg(target_os = "redox")'.dependencies]
redox_users = { version = "0.4", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = [
    "Win32_UI_Shell",
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_Com",
] }
winreg = "0.50.*"
windows = { version = "0.48.*", features = ["Foundation", "Devices_Geolocation"] }
