[[bin]]
required-features = ["binary"]
name = "weatherd"
path = "bin/weatherd.rs"

[[bin]]
required-features = ["support"]
name = "updater"
path = "bin/updater.rs"

[[bin]]
required-features = ["support", "installer"]
name = "installer"
path = "bin/installer.rs"

[[bin]]
required-features = ["binary"]
name = "weather"
path = "bin/weather.rs"


[lib]
name = "weather_core"
crate-type = [
    "cdylib",
    "rlib",
]

[package]
name = "weather"
version = "2023.5.6"
edition = "2021"
authors = ["Ashwin Naren"]
rust-version = "1.64.0"
description = "weather, in your terminal"
readme = "README.md"
homepage = "https://arihant2math.github.io/weathercli/"
repository = "https://github.com/arihant2math/weathercli"

[build-dependencies]
winresource = "0.1"
rustc_version = "0.4.0"

[dependencies]
auto-launch = { version = "0.4.0", optional = true, path = "./lib/auto-launch" }
bincode = "1.3.3"
clap = { version = "4.2", features = ["derive"] }
cookie_store = "0.19.0"
crossterm = "0.26"
dark-light = { version = "1.0.0", optional = true }
futures-util = { version = "0.3", optional = true }
hex = "0.4.*"
home = "0.5"
iced = { version = "0.9", features = ["image"], optional = true }
image = "0.24"
indicatif = { version = "0.17", optional = true }
libloading = "0.8"
log = "0.4"
log4rs = "1.2"
rayon = "1.7"
regex = "1.8"
reqwest = { version = "0.11", features = ["stream"], optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
simd-json = "0.9.2"
tokio = { version = "1.28", features = ["full"], optional = true }
ureq = { version = "2.6.2", default-features = false, features = ["tls", "gzip", "cookies", "json"], path = "./lib/ureq" }
url = "2.3"
wasmer = "3.3"

[dev-dependencies]
rand = "0.8.5"

[target.'cfg(windows)'.dependencies]
winreg = "0.50.*"
windows = { version = "0.48.*", features = ["Foundation", "Devices_Geolocation"] }

[features]
binary = ["dep:auto-launch"]
support = ["binary", "dep:tokio", "dep:futures-util", "dep:reqwest", "dep:indicatif"]
installer = ["binary"]
gui = ["binary", "dep:iced", "dep:dark-light"]
default = ["binary"]

[profile.bench]
debug = true
