[package]
name = "updater"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.14", features = ["stream"] }
futures-util = "0.3.27"
indicatif = "0.17.3"
tokio = { version = "1.26.0", features = ["full"] }
clap = { version = "4.1.8", features = ["derive"] }
