[package]
name = "updater"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.13", features = ["blocking", "stream"] }
futures-util = "0.3.14"
indicatif = "0.17.2"
tokio = { version = "1.23.0", features = ["full"] }
