name: Rust Builds

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'scripts/**'
      - 'icon/**'
      - 'docs_templates/**'
      - 'tests/**'
      - 'scripts/**'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'

    - name: Build with cargo
      run: cargo build -r --all-features

    - name: Fix weather icon windows
      if: startsWith(matrix.os, 'windows')
      run: ./rcedit ./target/release/weather.exe --set-icon .\icon\icon.ico

    - uses: actions/upload-artifact@v3
      name: Upload Updater (Windows)
      if: startsWith(matrix.os, 'windows')
      with:
        name: updater (Windows)
        path: ./target/release/updater.exe

    - uses: actions/upload-artifact@v3
      name: Upload Updater (Unix)
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: updater (Unix)
        path: ./target/release/updater

    - uses: actions/upload-artifact@v3
      name: Upload Weatherd (Windows)
      if: startsWith(matrix.os, 'windows')
      with:
        name: weatherd (Windows)
        path: ./target/release/weatherd.exe

    - uses: actions/upload-artifact@v3
      name: Upload Weatherd (Unix)
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: weatherd (Unix)
        path: ./target/release/weatherd

    - uses: actions/upload-artifact@v3
      name: Upload Installer (Windows)
      if: startsWith(matrix.os, 'windows')
      with:
        name: installer (Windows)
        path: ./target/release/installer.exe

    - uses: actions/upload-artifact@v3
      name: Upload Installer (Unix)
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: installer (Unix)
        path: ./target/release/installer

    - uses: actions/upload-artifact@v3
      name: Upload GUI Installer (Windows)
      if: startsWith(matrix.os, 'windows')
      with:
        name: GUI installer (Windows)
        path: ./target/release/gui_installer.exe

    - uses: actions/upload-artifact@v3
      name: Upload GUI Installer (Unix)
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: GUI installer (Unix)
        path: ./target/release/gui_installer

    - uses: actions/upload-artifact@v3
      name: Upload Weather (Windows)
      if: startsWith(matrix.os, 'windows')
      with:
        name: Weather (Windows)
        path: ./target/release/weather.exe

    - uses: actions/upload-artifact@v3
      name: Upload Weather (Unix)
      if: startsWith(matrix.os, 'ubuntu')
      with:
        name: Weather (Unix)
        path: ./target/release/weather