# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  windows-build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        maturin build -r
        $files = Get-ChildItem "target/wheels/"
        foreach ($f in $files) {
            pip install $f
        }
        pip install /target/wheels/weather_core-0.1.0-cp311-none-win_amd64.whl
    - name: Build with pyinstaller
      run: |
        pyinstaller -F weather.py
    - uses: actions/upload-artifact@v3
      with:
        name: weather.exe
        path: ./dist/weather.exe
  linux-build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install -r requirements.txt
        maturin build -r
        for file in target/wheels/*.whl
        do
          name=${file##*/}
          pip install "$pwd+$file"
        done
    - name: Build with pyinstaller
      run: |
        pyinstaller -F weather.py
    - uses: actions/upload-artifact@v3
      with:
        name: weather (Unix)
        path: ./dist/weather
