name: Update Website Data
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

jobs:
    update:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Install Requirements
          run:
            pip install requests
            pip install click
        - name: Update Executables
          run:
            python3 update_docs_templates.py "$GH_API_PAT"
          env:
            SUPER_SECRET: ${{secrets.GH_API_PAT}}
        - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
          with:
            default_author: github_actions
            message: 'Docs: Bumped Executables to latest version (Bot)'
